# Generated by Django 4.0 on 2022-02-22 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plastika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slika', models.ImageField(upload_to='')),
                ('type', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('temperature', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proizvodjac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('slikaa', models.ImageField(upload_to='')),
                ('type', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('website', models.URLField()),
                ('printer_plastika', models.ManyToManyField(to='main.Plastika')),
                ('printer_proizvodjac', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.proizvodjac')),
            ],
        ),
        migrations.AddField(
            model_name='plastika',
            name='plastika_proizvodjac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.proizvodjac'),
        ),
    ]
