# Generated by Django 4.0 on 2022-02-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_printer_slikaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='plastika',
            name='website',
            field=models.URLField(default='default@gmail.com'),
        ),
        migrations.AlterField(
            model_name='plastika',
            name='slika',
            field=models.ImageField(blank=True, default='815.jpg', null=True, upload_to=''),
        ),
    ]
